### ISSUE TITLE
Dictionary or Bool value in response

### ISSUE THREAD

**Issue by NBibikov** [EasyMapping/EasyMapping#113]
Hello!

Please help me!
I have some response from server. In one situation i have NSDictionary in response, other - bool value.
I need save value if there is dictionary and skip if bool. Is it possible?

[mapping mapKeyPath:@"acf.imageforcategory" toProperty:@"imageforcategory"];

```
{
    ID = 77;
    acf =     {
        imageforcategory = "http://xxx/wp-content/uploads/2015/09/image96.jpg";
    };
    count = 19;
```
```
{
    ID = 172;
    acf = 0;
    count = 1;
```
```
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<__NSCFBoolean 0x39fa658> valueForUndefinedKey:]: this class is not key value coding-compliant for the key imageforcategory.'
```

**Comment by lucasmedeirosleite** [comment]
You can use the method mapKeyPath:toProperty:withValueBlock: instead. 
Then instead of passing acf.imageforcategory as first argument pass only acf and then check its type.
Depending on the type return what you want in the value block.

But I strongly recommend not to pass different type values for the same property of the json on sever side.

**Comment by DenHeadless** [comment]
I'm closing this issue for now, thanks @lucasmedeirosleite!

**Comment by NBibikov** [comment]
Yes! Thank you very much! It works for me! Unfortunately i cann't change API and have need work with it
t
