### ISSUE TITLE
Received memory warning

### ISSUE THREAD

**Issue by Sh1mor1nka** [EasyMapping/EasyMapping#116]
I add to my CoreData about 20.000 objects.

i run these code in loop few times, maybe i shouldn't do these
```
EKManagedObjectMapping *mapping = ...;
    
    // create background context
    NSManagedObjectContext *private = [[NSManagedObjectContext alloc] initWithConcurrencyType:NSPrivateQueueConcurrencyType];
    [private setParentContext:[YControl sharedManagedObjectContext]];
    
    // add object to CoreData in private queue
    [private performBlock:^{
        NSDate *start = [NSDate date];
        [EKManagedObjectMapper arrayOfObjectsFromExternalRepresentation:array withMapping:mapping inManagedObjectContext:private];
        
        NSError *error = nil;
        if (![private save:&error]) {
            NSLog(@"Error saving context: %@\n%@", [error localizedDescription], [error userInfo]);
            abort();
        }

        NSLog(@"update time for %@: %f", table, [[NSDate date] timeIntervalSinceDate:start]);
    }];
```

and after i "Received memory warning", what can it bee? I don't have memory leaks. Thank you.

UPD: What is strange, that memory jumps to 1Gb, and then falls to 90mb, WTF?)

UPD: I found problem, server in one response gives me 11 thousands objects, and my memory jump to 1000, is there any ways to fix this except of changing the response objects count? 

UPD: line 202 in ```EKManagedObjectMapper``` have a fun with my memory :)

```
EKCoreDataImporter * importer = [EKCoreDataImporter importerWithMapping:mapping
                                                     externalRepresentation:externalRepresentation
                                                                    context:context];
```

**Comment by Sh1mor1nka** [comment]
I think i have memory problems because i use ```arrayOfObjectsFromExternalRepresentation```, i keep all references in array until it will be returned.

**Comment by DenHeadless** [comment]
11000 objects is very large for a mobile device. Even benchmarks we run on EasyMapping to determine it's perfomance, is 2000 objects on a Mac. 

You can try to profile your app in instruments to determine which data structures cause such a lot of memory consumption. It's possible that JSON this big can cause a memory warning, even without EasyMapping. Profiling really should be first and most important thing to do.

Another thing to do would be to parse each object on his own - replace arrayOfObjectsFromExternalRepresentation: with for loop. However this will make parsing incredibly slow, because it won't be optimized by our CoreDataImporter class.

And of course you can negotiate with your back-end developer to fix JSON this large. It's mobile devices after all, not PCs =)

**Comment by Sh1mor1nka** [comment]
Thank you for your answer Den!
About instruments.
I use instruments but i don't see any leaks, memory just growing, nothing suspicious, also i'm not very experienced in profiling, maybe i miss something.

About "parse each object on his own", i think it's the only way, because back-end developer sometimes send me array of same objects where same keys can be different types, number or string :)

So i think i will check if objects count in my JSON less then thousand i will call ```arrayOfObjectsFromExternalRepresentation``` otherwise i'll loop and create each element in ```@autoreleasepool {}``` here is good example in swift: http://stackoverflow.com/questions/32034100/memory-leak-with-large-core-data-batch-insert-in-swift

Thank you for your help!

**Comment by armandzwan** [comment]
What I did was splitting it up into batches and the loop over them. Say 100 (arrayOfObjectsFromExternalRepresentation) at a time in an @autoreleasepool.
