### ISSUE TITLE
Respect mutable properties

### ISSUE THREAD

**Issue by ajsharp** [EasyMapping/EasyMapping#98]
Currently, mutable properties (NSMutableDictionary, NSMutableArray, NSMutableSet) get mapped to their immutable counterparts when an object is instantiated from a json dict. Ideally, EasyMapping would know to instantiate the mutable versions of these properties.

**Comment by DenHeadless** [comment]
Thanks for suggestion, @ajsharp!

I have extended this a bit more, and added support for respecting foundation property types, adding NSSet, NSOrderedSet, and NSOrderedMutableSet to the mix.

Due to perfomance reasons, this behaviour is turned off, but it can be turned on by setting single property on EKObjectMapping to YES.

Please take a look at [0.15.0](https://github.com/EasyMapping/EasyMapping/releases/tag/0.15.0) release or commit 9bec955a.

**Comment by ajsharp** [comment]
@DenHeadless which property is it? It would be great to add this to the documentation.

**Comment by ajsharp** [comment]
Ah, nevermind, it's `respectPropertyFoundationTypes`. Thanks.
